name: Daily Stock Upload

on:
  schedule:
    - cron: '0 21 * * *'  # Runs every day at 08:00 UTC
  workflow_dispatch:      # Allows manual run

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run upload script
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          MARKETSTACK_API_KEY: ${{ secrets.MARKETSTACK_API_KEY }}
        run: python upload_to_dune.py
